### ISSUE TITLE
Broken CryptoTransferExample

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#103]
## Issue 

After running the [updated crypto transfer example](https://github.com/hashgraph/hedera-sdk-js/blob/master/examples/transfer-crypto.js) I'm getting the following error

```
(node:1854) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'maxTransactionFee' of undefined
    at new TransactionBuilder (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/TransactionBuilder.js:19:78)
    at new CryptoTransferTransaction (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/account/CryptoTransferTransaction.js:11:9)
    at main (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/new-example.js:23:14)
    at Object.<anonymous> (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/new-example.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:1854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Code to reproduce

```
require("dotenv").config();

const { Client, CryptoTransferTransaction } = require("@hashgraph/sdk");

async function main() {
  const operatorPrivateKey = process.env.OPERATOR_KEY;
  const operatorAccount = process.env.OPERATOR_ID;

  if (operatorPrivateKey == null || operatorAccount == null) {
    throw new Error(
      "environment variables OPERATOR_KEY and OPERATOR_ID must be present"
    );
  }

  const client = new Client({
    nodes: { "0.testnet.hedera.com:50211": "0.0.3" },
    operator: {
      account: operatorAccount,
      privateKey: operatorPrivateKey
    }
  });

  const tx = new CryptoTransferTransaction()
    .addSender(operatorAccount, 10)
    .addRecipient("0.0.3", 10)
    .setMemo("[sdk example] transfer to 0.0.3")
    .build(client);

  await tx.execute(client);
}

main();
```

## Suggested solution

Add a default value for `maxTransactionFee` so that leaving undefined doesn't result in errors.

We should have a tighter release process to ensure that the examples always work.

**Comment by mehcode** [comment]
`master` is not what is released. 

You are correct in that the release process should be more automated so we can ensure tags are being created. 

I pushed a tag for the last release: https://github.com/hashgraph/hedera-sdk-js/tree/v0.7.2
