### ISSUE TITLE
Help with Account Info Query

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#105]
Curious if this is just an issue on my end? If so, any suggestions on how to resolve? 🤞 

**Original issue**
When running the [get-account-info.js](https://github.com/hashgraph/hedera-sdk-js/blob/v0.7.2/examples/get-account-info.js) example for release `v.0.7.2` I get the following errors

```
node get-account-info.js
(node:1501) UnhandledPromiseRejectionWarning: Error: AccountInfoQuery failed validation:
`.setPayment()` required
    at Object.runValidation (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/util.js:100:15)
    at AccountInfoQuery.validate (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:56:16)
    at AccountInfoQuery.<anonymous> (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:106:18)
    at Generator.next (<anonymous>)
    at /Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:4:12)
    at AccountInfoQuery.execute (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:97:16)
    at /Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/get-account-info.js:21:108
    at Object.<anonymous> (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/get-account-info.js:22:2)
```
**Attempt to resolve** 
After receiving that error, I attempted to `setPayment(1000000)`, making the updated script 

```
require("dotenv").config();

const { AccountInfoQuery, Client } = require("@hashgraph/sdk");

const privateKey = process.env.OPERATOR_KEY;

if (!privateKey) {
  throw new Error("missing env var OPERATOR_KEY");
}

const client = new Client({
  operator: {
    account: { shard: 0, realm: 0, account: process.env.OPERATOR_ID },
    privateKey
  }
});

const accountId = { shard: 0, realm: 0, account: 3 };

(async function() {
  console.log(
    "account info:",
    JSON.stringify(
      await new AccountInfoQuery(client)
        .setAccountId(accountId)
        .setPayment(1000000)
        .execute()
    )
  );
})();

```

**Secondary issue**
Which then results in the following error 

```
(node:1518) UnhandledPromiseRejectionWarning: TypeError: c.toArray is not a function
    at Function.jspb.Message.setWrapperField (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/google-protobuf/google-protobuf.js:432:335)
    at proto.proto.QueryHeader.setPayment (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/generated/QueryHeader_pb.js:181:23)
    at AccountInfoQuery.setPayment (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/node_modules/@hashgraph/sdk/lib/QueryBuilder.js:52:22)
    at /Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/get-account-info.js:21:108
    at Object.<anonymous> (/Users/cooperkunz/Desktop/hide/Hedera-JS-Examples/test1/get-account-info.js:22:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3
```

`package.json` below, if it's of help
```
{
  "name": "test1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@hashgraph/sdk": "^0.7.2",
    "dotenv": "^8.2.0"
  }
}
```

**Comment by abonander** [comment]
@Cooper-Kunz you want to use `.setPaymentAmount` if you're passing in a raw number; `.setPayment` is for providing a pre-constructed payment transaction.

Leaving this open to address the second error which is pretty unhelpful.

**Comment by Cooper-Kunz** [comment]
Thanks for the clarity and quick response!
