### ISSUE TITLE
query to get the contents of a file throws an INVALID_NODE_ACCOUNT error

### ISSUE THREAD

**Issue by vijayshiyani** [hashgraph/hedera-sdk-js#1056]
### Description

Query to get the contents of a file throws an INVALID_NODE_ACCOUNT error.
it was working as expected until the previous version `2.11.3`

### Steps to reproduce

Run the following sample javascript file using node to reproduce it.  Make sure you use  @hashgraph/sdk version `2.12.0`

````javascript
const { Client, FileId, FileContentsQuery } = require("@hashgraph/sdk");

async function main() {
    const OPERATOR_ID = "0.0.1..";
    const OPERATOR_KEY =
        "302e02...";

    const client = Client.forTestnet();
    client.setOperator(OPERATOR_ID, OPERATOR_KEY);

    const FILE_ID = "0.0.34138267";

    const fileId = FileId.fromString(FILE_ID);

    //Create the query
    const query = new FileContentsQuery().setFileId(fileId);

    //Sign with client operator private key and submit the query to a Hedera network
    const contents = await query.execute(client);

    console.log(contents.toString());
}

main();
````

It throws the following error
````sh
PrecheckStatusError: transaction 0.0.12710106@1649307278.54165811 failed precheck with status INVALID_NODE_ACCOUNT
````

### Hedera network

testnet

### Version

v2.12.0

### Operating system

macOS

**Comment by mgarbs** [comment]
Commenting here to +1 this. I was helping out a guy trying to make a contract from the js sdk using v2.12.0. We both get the same error as your mentioning here. This is the code we are using:

```js
async function getMobileNum() {
    try {
        const client = getClient();
        const contractQueryTx = new ContractCallQuery()
            .setContractId("0.0.34144205")
            .setGas(100000)
            .setFunction("getMobileNumber", new ContractFunctionParameters().addString("Alice"))
            .setMaxQueryPayment(new Hbar(0.00000001));
        const contractQuerySubmit = await contractQueryTx.execute(client);
        const contractQueryResult = contractQuerySubmit.getUint256(0);
        console.log(`- Here's the phone number you asked for: ${contractQueryResult} \n`);
    } catch (error) {
        console.log(error)
    }
}
```

```
PrecheckStatusError: transaction 0.0.33958836@1649438746.396855095 failed precheck with status INVALID_NODE_ACCOUNT
    at new PrecheckStatusError (/Users/michaelgarber/Desktop/hbar-wallets/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)
    at ContractCallQuery._mapStatusError (/Users/michaelgarber/Desktop/hbar-wallets/node_modules/@hashgraph/sdk/lib/query/Query.cjs:382:12)
    at ContractCallQuery.execute (/Users/michaelgarber/Desktop/hbar-wallets/node_modules/@hashgraph/sdk/lib/Executable.cjs:468:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getMobileNum (/Users/michaelgarber/Desktop/hbar-wallets/services/scService.js:74:37)
    at async /Users/michaelgarber/Desktop/hbar-wallets/routes/scRouter.js:38:25 {
  status: Status { _code: 3 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: [Long],
      realm: [Long],
      num: [Long],
      aliasKey: null,
      _checksum: null
    },
    validStart: Timestamp { seconds: [Long], nanos: [Long] },
    scheduled: false,
    nonce: null
  }
}
```
When I downgrade to the js sdk v2.11.3 I do not get this error.

**Comment by danielakhterov** [comment]
This was a result of a de-sync between `main` and `develop` :( The error was that `nodeAccountIds` were being set correctly on each request attempt and when fetching costs the node account IDs were being locked incorrectly. Also, the second part of this issue is that the operator was not being saved for paid queries which meant when rebuilding payment transactions an account ID of `0.0.0` was being used as the payer. Should be fixed https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.12.1 A test was added to hopefully prevent this from happening again here: https://github.com/hashgraph/hedera-sdk-js/blob/ebe921453fb815436b14bead470321cdbf62a50b/test/unit/AccountInfoMocking.js#L54
