### ISSUE TITLE
WebClient does not support consensus service topic subscription

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-sdk-js#1114]
### Description

[`WebClient` ](https://github.com/hashgraph/hedera-sdk-js/blob/3240cd5c1ddef1eab1b796d0a4b44f23c884621f/src/client/WebClient.js#L196)does not support consensus service subscription because it does not implement `setMirrorNode` properly.

### Steps to reproduce

Just use the following code from the example with `React` or any frontend framework `Vue`, `Angular`
```
//Create the query to subscribe to a topic
new TopicMessageQuery()
    .setTopicId(topicId)
    .subscribe(client, null, (message) => {
        let messageAsString = Buffer.from(message.contents, "utf8").toString();
        console.log(`${message.consensusTimestamp.toDate()} Received: ${messageAsString}`);
    });
```
and will get the following error
```
TopicMessageQuery.js:371 Uncaught TypeError: Cannot read properties of undefined (reading '_mirrorNetwork')
    at TopicMessageQuery._makeServerStreamRequest (TopicMessageQuery.js:371:1)
    at TopicMessageQuery.subscribe (TopicMessageQuery.js:336:1)
    at subscribeTopic (ConsensusService.jsx:24:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4284:1)
    at executeDispatch (react-dom.development.js:9011:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9043:1)
    at processDispatchQueue (react-dom.development.js:9056:1)
```

### Additional context

[`NodeClient`](https://github.com/hashgraph/hedera-sdk-js/blob/3240cd5c1ddef1eab1b796d0a4b44f23c884621f/src/client/NodeClient.js#L288) does not have this problem. 

### Hedera network

testnet

### Version

v2.13.1

### Operating system

macOS

**Comment by mehcode** [comment]
Not a bug. The mirror nodes do not support gRPC-web and browser usage.
