### ISSUE TITLE
calling erc20 contract function -> TypeError: client._network.decreaseBackoff is not a function, TypeError: Cannot read properties of undefined (reading '_code')

### ISSUE THREAD

**Issue by isaacadams** [hashgraph/hedera-sdk-js#1119]
Running into an issue when calling `balanceOf` from an erc20 contract on the testnet

### ℹ️ Relevant Dependencies

```json5
// package.json
{
 ...,
   "dependencies": {
      "@hashgraph/hethers": "^1.1.0",
      "@hashgraph/sdk": "^2.13.1",
   }
 ...,
}
```

❗ NOTE: This error does not occur in `"@hashgraph/sdk": "2.10.0"`

### 🚨 Error

https://github.com/hashgraph/hedera-sdk-js/blob/f065cb1568191a546e8b4e8a52b7867149badc53/src/Executable.js#L486

```
TypeError: client._network.decreaseBackoff is not a function
    at ContractCallQuery.execute (C:\source\hdn\hodl-deez-nuts\node_modules\@hashgraph\sdk\lib\Executable.cjs:481:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:103
    switch (error.status._code) {
                         ^

TypeError: Cannot read properties of undefined (reading '_code')
    at checkError (C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:103:26)
    at Wallet.<anonymous> (C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:252:47)
    at step (C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:78:23)
    at Object.throw (C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:59:53)
    at rejected (C:\source\hdn\hodl-deez-nuts\node_modules\@hethers\abstract-signer\lib\index.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 📔 Steps to Reproduce

```javascript
/**
 * this account is the one that deployed the contract onto testnet
 * NOTE: this private key for the signer account was generated using PrivateKey.generateECDSA()
 * @returns {{ accountId: string, privateKey: string }}
 */
function getSigner() {
  return JSON.parse(require('fs').readFileSync('./signer.json'));
}

/**
 * @param {string} the address of the erc20 contract, e.g. 0x00000000000000000000000000000000000xxxxx
 * @param {object} the abi of the erc20 contract
 */
async function checkBalance(contractAddress, abi) {
  const provider = hethers.providers.getDefaultProvider('testnet');
  const { accountId, privateKey } = getSigner();
  const wallet = new hethers.Wallet(
    {
      account: accountId, // e.g. 0.0.xxxxxxxx
      privateKey: privateKey, // e.g. e.g. 0x00000000000000000000000000000000000xxxxx
    },
    provider
  );

  const contract = new hethers.Contract(contractAddress, abi, wallet);

  const balance = await contract.balanceOf(wallet.address, {
    gasLimit: 100000,
  });
  console.log(balance.toString());
}
```

**Comment by danielakhterov** [comment]
I believe the issue is that you should be using the same version of the SDK as `@hashgraph/heathers` because they're on a beta release and are not up to date with the latest release.

**Comment by isaacadams** [comment]
> I believe the issue is that you should be using the same version of the SDK as `@hashgraph/heathers` because they're on a beta release and are not up to date with the latest release.

Ah, I see what you are saying. That makes sense.

Since `@hashgraph/hethers` depends on `@hashgraph/sdk`, shouldn't the compatible version of  `@hashgraph/sdk` be made a peer dependency of `@hashgraph/hethers`?

**Comment by danielakhterov** [comment]
Hmm, peer dependency might be right, but I think the issue in particular here is that they're using a beta version. If they were using the latest stable version then the API should not be broken between stable version and hence should allow you to use a different stable version of the SDK; I say "should" because there have been times where we had a breaking change on a stable release.
