### ISSUE TITLE
Unable to rebuild transaction from bytes using fromBytes()

### ISSUE THREAD

**Issue by ah-7** [hashgraph/hedera-sdk-js#1171]
### Description

Rebuilding this transaction from bytes after converting it to bytes produces an error.

### Steps to reproduce

```
const transaction = new AccountAllowanceDeleteTransaction()
            .deleteAllTokenNftAllowances(new NftId(TokenId.fromString(tokenId), serialNo), operatorId)

let transId = TransactionId.generate(operatorId)
transaction.setNodeAccountIds([new AccountId(3)])
transaction.setTransactionId(transId);

transaction.freeze();

let transBytes = transaction.toBytes();

let tx = Transaction.fromBytes(transBytes)
```

### Additional context

@hashgraph/sdk/src/account/AccountId.js:116
        if (id.alias != null) {
               ^

TypeError: Cannot read properties of undefined (reading 'alias')
    at Function._fromProtobuf (/node_modules/@hashgraph/sdk/src/account/AccountId.js:116:16)
    at Function._fromProtobuf (/node_modules/@hashgraph/sdk/src/account/TokenNftAllowance.js:100:41)
    at  /node_modules/@hashgraph/sdk/src/account/AccountAllowanceDeleteTransaction.js:98:39
    at Array.map (<anonymous>)
    at _fromProtobuf (/node_modules/@hashgraph/sdk/src/account/AccountAllowanceDeleteTransaction.js:97:19)
    at Function.fromBytes (/node_modules/@hashgraph/sdk/src/transaction/Transaction.js:325:16)

### Hedera network

mainnet

### Version

2.16.1

**Comment by danielakhterov** [comment]
Released in https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.16.2
However, admittedly we should have a better test for all transaction from/to bytes, but that is a separate issue #1123
