### ISSUE TITLE
[help] FileCreateTransaction is asking to setFile before it exists?

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#125]
I'm attempting to create a file on release `v.0.8.0-beta-0` and getting the following error. 

```
(node:2981) UnhandledPromiseRejectionWarning: Error: FileCreateTransaction failed validation:
FileCreateTransaction must have a file set
    at Object.runValidation (/Users/cooperkunz/Desktop/Hedera-JS-Examples/js-sdk/node_modules/@hashgraph/sdk/lib/util.js:100:15)
    at FileCreateTransaction.validate (/Users/cooperkunz/Desktop/Hedera-JS-Examples/js-sdk/node_modules/@hashgraph/sdk/lib/TransactionBuilder.js:45:16)
    at FileCreateTransaction.build (/Users/cooperkunz/Desktop/Hedera-JS-Examples/js-sdk/node_modules/@hashgraph/sdk/lib/TransactionBuilder.js:79:14)
    at main (/Users/cooperkunz/Desktop/Hedera-JS-Examples/js-sdk/file-create.js:25:6)
    at Object.<anonymous> (/Users/cooperkunz/Desktop/Hedera-JS-Examples/js-sdk/file-create.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

When running a FileCreateTransaction, why would it expect to have a FileID already set?

**Details**
There are no examples for using the file service [within the repository](https://github.com/hashgraph/hedera-sdk-js/tree/v0.8.0-beta.0/examples), but I expected the [FileCreateTransaction Test](https://github.com/hashgraph/hedera-sdk-js/blob/v0.8.0-beta.0/__tests__/file/FileCreateTransaction.test.ts) would have been a good indicator for desired behavior. I have now attempted to run this test, and it doesn't appear to be working itself.

The code I would like to work is as follows. 

```
require("dotenv").config();

const { Client, FileCreateTransaction } = require("@hashgraph/sdk");

async function main() {
  const operatorPrivateKey = process.env.OPERATOR_KEY;
  const operatorAccount = process.env.OPERATOR_ID;

  if (operatorPrivateKey == null || operatorAccount == null) {
    throw new Error(
      "environment variables OPERATOR_KEY and OPERATOR_ID must be present"
    );
  }

  const client = new Client({
    network: { "0.testnet.hedera.com:50211": "0.0.3" },
    operator: {
      account: operatorAccount,
      privateKey: operatorPrivateKey
    }
  });

  const transaction = new FileCreateTransaction()
    .setContents("testing file create transaction")
    .build(client);

  console.log(await transaction.execute(client));
}

main();
```

I would hope to run the above with defaults for fees, operator, no admin key, etc. and then the return value of the transaction execution (record/receipt/etc, whatever it is) would give me the File ID. Similarly to the Java SDK [example](https://docs.hedera.com/reference#file-service-transactions-create-file).

**Comment by abonander** [comment]
The error message is misleading, it's actually erroring because there's no keys set, but that's allowed by the network so the entire validation error should just be removed.

**Comment by mehcode** [comment]
Fixed on master, release pending

**Comment by Cooper-Kunz** [comment]
Thanks for the quick help! 🎊
