### ISSUE TITLE
Error: failed precheck with status INVALID_SIGNATURE

### ISSUE THREAD

**Issue by JulissaDantes** [hashgraph/hedera-sdk-js#1264]
### Description

I was trying to verify is the self destruct function worked by calling ContractInfoQuery and check the isDeleted property, but instead I got that error.

### Steps to reproduce

1. Function am calling:
```
    function contractSizeFunction(bytes memory code) external returns(address addr){

        assembly {
            addr := create(0,add(code,0x20), mload(code))
        }
        return addr;
    }
```
2. Test code:
```
const client = Client.forTestnet().setOperator(process.env.OPERATOR_ACCOUNT_ID!, process.env.OPERATOR_PRIVATE_KEY!).setDefaultMaxTransactionFee(new Hbar(10));
      const tx = await delegator.delegateDestructFunction();
      await tx.wait();

      const { isDeleted } = await new ContractInfoQuery()
      .setContractId(contractID)
      .execute(client);

      expect(isDeleted).to.be.true;
```

### Additional context

Stack trace of the error:
```
StatusError: transaction 0.0.48224935@1663169183.182199493 failed precheck with status INVALID_SIGNATURE
      at new PrecheckStatusError (node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:43:5)
      at ContractInfoQuery._mapStatusError (node_modules/@hashgraph/sdk/lib/query/Query.cjs:500:12)
      at ContractInfoQuery.execute (node_modules/@hashgraph/sdk/lib/Executable.cjs:690:22)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (test/opcodes.test.ts:560:29)
```

### Hedera network

testnet

### Version

1

### Operating system

macOS

**Comment by danielakhterov** [comment]
This doesn't seem to be an SDK bug. The `INVALID_SIGNATURE` is returned by the consensus nodes. I would recommend posting this issue in https://github.com/hashgraph/hedera-services
