### ISSUE TITLE
Unhandled error when making a ContractCallLocal with a large result

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-sdk-js#1349]
### Description

The error was found when debugging [Relay Issue [#533](https://github.com/hashgraph/hedera-json-rpc-relay/issues/533)](Size limit on call result return value to view pure function).

### Steps to reproduce

1. Setup a local instance of the relay and configure it to work with `testnet`
2. Run the CURL request from the linked issue.
3. SDK throws the following error:
```
TypeError: Cannot read properties of null (reading 'contractID')
    at Function._fromProtobuf (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/contract/ContractFunctionResult.cjs:179:12)
    at ContractCallQuery._mapResponseSync (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/contract/ContractCallQuery.cjs:352:44)
    at ContractCallQuery._mapStatusError (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/contract/ContractCallQuery.cjs:275:41)
    at ContractCallQuery.execute (.../hedera-json-rpc-relay/packages/relay/node_modules/@hashgraph/sdk/lib/Executable.cjs:696:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Hedera network

testnet

### Version

2.18.5

### Operating system

None

**Comment by petreze** [comment]
After some testing and debugging, the issue was not encountered and it seems that it is not present. Since this is the case, I'm closing the issue

**Comment by mshakeg** [comment]
Hi @petreze [hedera-json-rpc-relay/533](https://github.com/hashgraph/hedera-json-rpc-relay/issues/533) is still an issue.

**Comment by Kalina-Todorova** [comment]
Reopening this to further investigate.
