### ISSUE TITLE
Error("list is locked") when trying to sign a transaction

### ISSUE THREAD

**Issue by bamzedev** [hashgraph/hedera-sdk-js#1410]
### Description

When I try to sign a transaction, I get the error `new Error("list is locked");`. This only happens if I have called `getTransactionHash()`, before trying to sign it.

### Steps to reproduce

```
const transaction = await new TransferTransaction()
        .addHbarTransfer(accountId, new Hbar(0.001).negated())
        .addHbarTransfer(aliasAccountId, new Hbar(0.001))
       .freezeWith(client);
 await transaction.getTransactionHash()
await transaction.signWithOperator(client)```

### Additional context

```
Error: list is locked
    at List.clear (file:///Users/user/development/work/hedera/hedera-sdk-js/src/transaction/List.js:86:19)
    at TransferTransaction.signWith (file:///Users/user/development/work/hedera/hedera-sdk-js/src/transaction/Transaction.js:658:28)
    at TransferTransaction.signWithOperator (file:///Users/user/development/work/hedera/hedera-sdk-js/src/transaction/Transaction.js:724:21)
```

### Hedera network

testnet

### Version

v2.19.2

### Operating system

macOS

**Comment by vea-vecturne** [comment]
I'm seeing this or something similar to this downstream in hethers.js in base-provider.ts:sendTransaction.  It doesn't sign the transaction in that function, but it does call getTransactionHash then executes the transaction with a client.  I get the same error: list is locked.

**Comment by littletarzan** [comment]
Is there an ETA on this fix? This bug is causing us significant issues unit testing smart contracts.

**Comment by petreze** [comment]
@littletarzan @Nana-EC 
Hello, this issue will be fixed with the mentioned PR but just keep in mind that the transaction hash which you will get before signing will differ from the one in the `TransactionResponse`. This is because when we add a new signer to the transaction, the hash will change and won't be the same as the one which you will get after execution. Furthermore, the transaction hash after execution will contain the node against which the transaction has been actually executed
