### ISSUE TITLE
Test related to execution of contract when gas is not set is failing

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-sdk-js#1734]
### Description

This issue started after updates were made to the Hedera services. To resolve this, we need to expect a PrecheckStatusException instead of a ReceiptStatusException in such cases

### Steps to reproduce

Run the test that verifies the execution of the contract when gas is not set
[Reference](https://github.com/hashgraph/hedera-sdk-java/issues/1503)

### Additional context

```
ContractExecuteIntegrationTest > Cannot execute contract when gas is not set FAILED
    java.lang.AssertionError: 
    Expecting actual throwable to be an instance of:
      com.hedera.hashgraph.sdk.ReceiptStatusException
    but was:
      com.hedera.hashgraph.sdk.PrecheckStatusException: Hedera transaction `0.0.1022@1690192724.679260153` failed pre-check with the status `INSUFFICIENT_GAS`
    	at com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapStatusException(Executable.java:908)
    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:447)
    	at com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:54)
    	...(91 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
        at ContractExecuteIntegrationTest.cannotExecuteContractWhenGasIsNotSet(ContractExecuteIntegrationTest.java:152)
```

### Hedera network

mainnet, testnet, previewnet

### Version

v2.30.0

### Operating system

macOS

**Comment by petreze** [comment]
Not needed as the test checks only for the `Status` being `INSUFFICIENT_GAS ` but not whether or not the error is `PrecheckStatusError` or `ReceiptStatusError`
