### ISSUE TITLE
fix: AccountId.toStringWithChecksum() errors

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-sdk-js#1803]
### Description

- `AccountId.toStringWithChecksum()` errors when invoked

### Steps to reproduce

(1) Install the following dependencies:

```json
{
    "type": "module",
    "dependencies": {
        "@hashgraph/sdk": "2.31.0",
        "dotenv": "16.3.1"
    }
}
```

(2) run the following script

```js
import {
    Client,
    AccountId,
    PrivateKey,
} from '@hashgraph/sdk';
import dotenv from 'dotenv';

dotenv.config();

if (!process.env.OPERATOR_ID || !process.env.OPERATOR_KEY) {
    throw new Error('Must set OPERATOR_ID and OPERATOR_KEY in .env');
}
const operatorId = AccountId.fromString(process.env.OPERATOR_ID);
const operatorKey = PrivateKey.fromString(process.env.OPERATOR_KEY);
const client = Client.forTestnet().setOperator(operatorId, operatorKey);

async function main() {
    console.log('Operator Account ID:', operatorId.toString());
    console.log('Operator Account ID with checksum:', operatorId.toStringWithChecksum());

    process.exit(0);
}

main();
```

(3) Observe the output:
- `operatorId.toString()` succeeds
- `operatorId.toStringWithChecksum()` fails with this error

```text
node_modules/@hashgraph/sdk/src/EntityIdHelper.js:397
    if (client._network._ledgerId == null) {
               ^

TypeError: Cannot read properties of undefined (reading '_network')
    at Module.toStringWithChecksum (file:///Users/user/code/hedera/hedera-code-snippets/multisig-account/node_modules/@hashgraph/sdk/src/EntityIdHelper.js:397:16)
    at AccountId.toStringWithChecksum (file:///Users/user/code/hedera/hedera-code-snippets/multisig-account/node_modules/@hashgraph/sdk/src/account/AccountId.js:297:26)
    at main (file:///Users/user/code/hedera/hedera-code-snippets/multisig-account/multisig-1-of-2.js:24:52)
    at file:///Users/user/code/hedera/hedera-code-snippets/multisig-account/multisig-1-of-2.js:29:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0
```

### Hedera network

testnet

### Version

0.31.0

### Operating system

macOS

**Comment by petreze** [comment]
This is normal behaviour - you are supposed to pass the `client` to the method in order to get the `_network` value. I just added a handler to indicate this to the users as well
