### ISSUE TITLE
Triage errors observed by using JS SDK

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1823]
### Description

There are a few different errors observed by @haris-evolt-dev, @adnanhodz and @ZerinRizEvolt.

- The python SDK, that is a wrapper around the Hedera Java SDK, was working fine and then experienced a timeout error
- The team then used the Hedera JS SDK to rule out any issues with the python SDK
- The team observed the timeout error when the Hedera JS SDK was being used 
- It sounds like everything was working at one point last week (which example was working?) and something changed in the last several days in which the errors are being observed.

Errors to investigate:

**TIMEOUT**
Error causes: The problem may be your internet connection, website server, browser, or firewall settings. Generally, a browser needs about 30 seconds to reach a website's server.

There was mention in the Telegram thread about a timeout error early on, however the most recent errors shown in the screenshots are `ECONNRESET`. Is the `TIMEOUT` error still being observed?

**Max attempts of 10 was reached for request with last error being**
This max number of attempts for a transaction has a default value of 10 in the SDK. This value can be modified to a higher value.

Is this error still being observed?

**ECONNRESET**
This error was observed when using https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/create-account.js and
https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/create-account-with-alias.js.

```
(node:26272) UnhandledPromiseRejectionWarning: Error: max attempts of 10 was reached for request with last error being: GrpcServiceError: read ECONNRESET
    at AccountCreateTransaction.execute (C:\a\hedera-create-account\node_modules\@hashgraph\sdk\lib\Executable.cjs:679:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ections_mode). (rejection id: 1)
```

Confirm is this error is the only one that is still being observed.

**Sample Code**
This below is the sample code the team has provided in the TG chat. 

```

const {
    Wallet,
    LocalProvider,
    PrivateKey,
    AccountCreateTransaction,
    Hbar,
} = require("@hashgraph/sdk");
require("dotenv").config();
// dotenv.config();
async function main() {
    if (process.env.OPERATOR_ID == null || process.env.OPERATOR_KEY == null) {
        throw new Error(
            "Environment variables OPERATOR_ID, and OPERATOR_KEY are required."
        );
    }
    const wallet = new Wallet(
        process.env.OPERATOR_ID,
        process.env.OPERATOR_KEY,
        new LocalProvider()
    );
    const newKey = PrivateKey.generate();
    console.log(`private key = ${newKey.toString()}`);
    console.log(`public key = ${newKey.publicKey.toString()}`);
    let transaction = await new AccountCreateTransaction()
        .setInitialBalance(new Hbar(10)) // 10 h
        .setKey(newKey.publicKey)
        .freezeWithSigner(wallet);
    transaction = await transaction.signWithSigner(wallet);
    const response = await transaction.executeWithSigner(wallet);
    const receipt = await response.getReceiptWithSigner(wallet);
    console.log(`account id = ${receipt.accountId.toString()}`);
}
void main();
```

### Steps to reproduce

Team to provide the code that is being used to reproduce the errors. 

### Hedera network

testnet

### Version

v2.32.0

### Operating system

None

**Comment by SimiHunjan** [comment]
I can create an account using the below sample code on testnet and do not observe any of the above errors. The below has testnet account and keys from the Hedera portal.

```
const {
    Wallet,
    LocalProvider,
    PrivateKey,
    AccountCreateTransaction,
    Hbar,
    AccountId,
} = require("@hashgraph/sdk");

require('dotenv').config();

async function main() {

    const wallet = new Wallet( AccountId.fromString("485575"),
        PrivateKey.fromStringED25519("302e020100300506032b65700422042012a4a4add3d885bd61d7ce5cff88c5ef2d510651add00a7f64cb90de3359bc5e"),
        new LocalProvider()
    )

    const newKey = PrivateKey.generate();

    console.log(`private key = ${newKey.toString()}`);
    console.log(`public key = ${newKey.publicKey.toString()}`);

    let transaction = await new AccountCreateTransaction()
        .setInitialBalance(new Hbar(10)) // 10 hbar
        .setKey(newKey.publicKey)
        .freezeWithSigner(wallet);

    transaction = await transaction.signWithSigner(wallet);

    const response = await transaction.executeWithSigner(wallet);

    const receipt = await response.getReceiptWithSigner(wallet);

    console.log(`account id = ${receipt.accountId.toString()}`);
}

void main();
```

**Comment by SimiHunjan** [comment]
I also ran the example provided by the team and it worked fine for me.


```
const {
    Wallet,
    LocalProvider,
    PrivateKey,
    AccountCreateTransaction,
    Hbar,
} = require("@hashgraph/sdk");
require("dotenv").config();
// dotenv.config();
async function main() {
    if (process.env.OPERATOR_ID == null || process.env.OPERATOR_KEY == null) {
        throw new Error(
            "Environment variables OPERATOR_ID, and OPERATOR_KEY are required."
        );
    }
    const wallet = new Wallet(
        process.env.OPERATOR_ID,
        process.env.OPERATOR_KEY,
        new LocalProvider()
    );
    const newKey = PrivateKey.generate();
    console.log(`private key = ${newKey.toString()}`);
    console.log(`public key = ${newKey.publicKey.toString()}`);
    let transaction = await new AccountCreateTransaction()
        .setInitialBalance(new Hbar(10)) // 10 h
        .setKey(newKey.publicKey)
        .freezeWithSigner(wallet);
    transaction = await transaction.signWithSigner(wallet);
    const response = await transaction.executeWithSigner(wallet);
    const receipt = await response.getReceiptWithSigner(wallet);
    console.log(`account id = ${receipt.accountId.toString()}`);
}
void main();
```

```
user@admins-Laptop hello-hedera-js-sdk % node createAccountTest.js 
private key = 302e020100300506032b65700422042044372be0dfd304fa46e61ea0d23cb5b7afbeb331815e17cdc920c933b12291fa
public key = 302a300506032b657003210027b400f07d6fb7bfaacb5fc9203a3c76ba91f5238eb736f44cab68b2f7137670
account id = 0.0.1126957
```

**Comment by SimiHunjan** [comment]
Error provided by dev team:

```
c:\a\hedera-create-account>node --version && npm start
v18.17.0
hedera-create-account@1.0.0 start
node create-account.js
private key = 302e020100300506032b65700422042061df2430f04e1cddea6b93ae3cfcbd4aeb79f971d5797a314326b06232f8fab1
public key = 302a300506032b657003210011a598eebefe1df8c7c2c61d66f4ece4fc326ae1a5560a0ab900198308f0d944
c:\a\hedera-create-account\node_modules\@hashgraph\sdk\lib\Executable.cjs:679
    throw new Error(`max attempts of ${maxAttempts.toString()} was reached for request with last error being: ${persistentError != null ? persistentError.toString() : ""}`);
          ^
Error: max attempts of 10 was reached for request with last error being: GrpcServiceError: read ECONNRESET
    at AccountCreateTransaction.execute (c:\a\hedera-create-account\node_modules\@hashgraph\sdk\lib\Executable.cjs:679:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (c:\a\hedera-create-account\create-account.js:37:22)
Node.js v18.17.0
```

**Comment by SimiHunjan** [comment]
This issue has been resolve. 

There is a U.S. nexus, transactions involving certain OFAC sanctioned jurisdictions are blocked from access, and as part of a technical update, some IP addresses not linked to those regions were blocked. This issue was resolved by removing the teams IPs from being blocked.

None of the above errors were no longer observed after the IPs were removed for the block list.
