### ISSUE TITLE
Crash when trying to get ContractId from evmAddress

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-sdk-js#1991]
### Description

When trying to get a a `ContractId` from an evmAddress it fails with the following error:
```
❯ node index.js
The smart contract byte code file ID is 0.0.5735029
The smart contract ID is 0.0.5735030
The smart contract solidity address is 0000000000000000000000000000000000578276
node:buffer:465
function fromStringFast(string, ops) {
                       ^

RangeError: Maximum call stack size exceeded
    at fromStringFast (node:buffer:465:24)
    at fromString (node:buffer:498:10)
    at Function.from (node:buffer:308:12)
    at Object.decode (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/encoding/hex.cjs:43:17)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:78:42)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:79:19)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:79:19)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:79:19)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:79:19)
    at ContractId.fromEvmAddress (/Users/user/Test/issue-sdk/node_modules/@hashgraph/sdk/lib/contract/ContractId.cjs:79:19)
```

Command with issue:
```
const contractIdfromEVMAddress = ContractId.fromEvmAddress(0, 0, solidityAddress);
```

### Steps to reproduce

Run the attached project

### Additional context

[issue-sdk.zip](https://github.com/hashgraph/hedera-sdk-js/files/13048371/issue-sdk.zip)

### Hedera network

mainnet, testnet, previewnet, other

### Version

v2.36.0

### Operating system

macOS

**Comment by iron4548** [comment]
Use ContractId.fromSolidityAddress('0000000000000000000000000000000000578276')

**Comment by SimiHunjan** [comment]
Do we need to add more api doc comments for how .fromEVMAddress() is intended to be used? I think this issue is coming up a few times. Maybe add that use .fromSolidityAddress() if you are looking to do x.

**Comment by iron4548** [comment]
> Do we need to add more api doc comments for how .fromEVMAddress() is intended to be used? I think this issue is coming up a few times. Maybe add that use .fromSolidityAddress() if you are looking to do x.

I think if we can have one function (fromEVMAddress) that can take in a CREATE2 EVM address, a EVM address, a solidity address would reduce the confusion about what to use. And just handle the conversion behind the scene by detecting what it is.
