### ISSUE TITLE
_toProto TypeError when calling setTopicId for consensus functions.

### ISSUE THREAD

**Issue by trevorlinan** [hashgraph/hedera-sdk-js#216]
When calling the _setTopicId_ method on _ConsensusTopicInfoQuery_ or _MirrorConsensusTopicQuery_, it throws a type error of not a function.

**Example:** 
````
async function getTopicInfo() {
	try {
		const topicInfo = await new ConsensusTopicInfoQuery()
			.setTopicId(<topidId>)
			.execute(<client>);
	} catch (err) {
		console.error(err);
	}
}
````

**Response:**
````
TypeError: id._toProto is not a function
    at ConsensusTopicInfoQuery.setTopicId (<path>/node_modules/@hashgraph/sdk/lib/consensus/ConsensusTopicInfoQuery.js:18:37)
    at getTopicInfo (<path>/index.js:58:5)
    at Object.<anonymous> (<path>/index.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
````

**Comment by mehcode** [comment]
Fixed on master, pending release
