### ISSUE TITLE
Error: Cannot find module '@improbable-eng/grpc-web-node-http-transport/lib'

### ISSUE THREAD

**Issue by ilyakmet** [hashgraph/hedera-sdk-js#23]
I'm trying to check the balance:

```js
const { Client } = require("@hashgraph/sdk");

const privateKey = "<pkey>";

const client = new Client({
    operator: {
        account: {shard: 0, realm: 0, account: <acocountId>},
        privateKey
    }
});

(async function () {
    console.log('account balance:', (await client.getAccountBalance()).toString());
})();
```

Error:
```bash
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '@improbable-eng/grpc-web-node-http-transport/lib'
Require stack:
- /Users/ilya/Documents/GitHub/hederaTestJs/node_modules/@hashgraph/sdk/index-node.js
- /Users/ilya/Documents/GitHub/hederaTestJs/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ilya/Documents/GitHub/hederaTestJs/node_modules/@hashgraph/sdk/index-node.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
```

**Comment by abonander** [comment]
@ilyakmet Please upgrade to 0.3.2. It removes the need for the Envoy proxy in Node.js as we can connect directly to the Hedera network. You specify a list of node addresses and account IDs to connect to just like the Java SDK.
