### ISSUE TITLE
Unable to subscribe to mirror with .setStartTime

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#249]
Hi, whenever and whatever I put into the `.setStartTime` method of a `MirrorConsensusTopicQuery`, I get an error as per below.

For reference, I store the last consensus time in a database (SQLITE) DATE field, and debugging shows my lastConsensusTime variable to be a valid date corresponding to the last consensus timestamp.

```
{
  "message": "Assertion failed",
  "reportErrorToServer": true,
  "messagePattern": "Assertion failed"
}
"AssertionError: Assertion failed\n    at new goog.asserts.AssertionError (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:81:876)\n    at Object.goog.asserts.doAssertFailure_ (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:82:257)\n    at Object.goog.asserts.assert (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:83:83)\n    at jspb.BinaryEncoder.writeSignedVarint64 (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:459:75)\n    at jspb.BinaryWriter.writeSignedVarint64_ (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:481:151)\n    at jspb.BinaryWriter.writeInt64 (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:484:159)\n    at proto.proto.Timestamp.serializeBinaryToWriter (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/@hashgraph/sdk/lib/generated/Timestamp_pb.js:168:12)\n    at jspb.BinaryWriter.writeMessage (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/google-protobuf/google-protobuf.js:493:479)\n    at Function.proto.com.hedera.mirror.api.proto.ConsensusTopicQuery.serializeBinaryToWriter (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/@hashgraph/sdk/lib/generated/MirrorConsensusService_pb.js:193:12)\n    at proto.com.hedera.mirror.api.proto.ConsensusTopicQuery.serializeBinary (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/@hashgraph/sdk/lib/generated/MirrorConsensusService_pb.js:169:57)\n    at /Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/@hashgraph/sdk/lib/mirror/node/MirrorConsensusTopicQuery.js:11:244\n    at Object.final_requester.sendMessage (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client_interceptors.js:1037:21)\n    at InterceptingCall._callNext (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client_interceptors.js:419:43)\n    at InterceptingCall.sendMessage (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client_interceptors.js:464:8)\n    at InterceptingCall._callNext (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client_interceptors.js:428:12)\n    at InterceptingCall.sendMessage (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client_interceptors.js:464:8)\n    at Client.makeServerStreamRequest (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/grpc/src/client.js:770:21)\n    at MirrorConsensusTopicQuery.subscribe (/Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/node_modules/@hashgraph/sdk/lib/mirror/node/MirrorConsensusTopicQuery.js:11:41)\n    at /Users/gregscullard/dev/github.com/hashgraph/hedera-hcs-token-example/javascript/hedera-hcs-token-example-server/mirror.js:41:18"
```

**Comment by mehcode** [comment]
@gregscullard Do you have more details on the context of the error there? What does the invocation to `setStartTime` look like?

**Comment by mehcode** [comment]
It has to be a Date not a number. SQLite is going to return a string. We've added some error checking on the type for that function.

https://github.com/hashgraph/hedera-sdk-js/blob/90d43aabcd5bbb64f509a54248a8b6e137a14295/src/Time.ts#L16-L30
