### ISSUE TITLE
v2.0.5 returning error for token info query

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#303]
```
    //Create the query
    const query2 = new TokenInfoQuery()
    .setTokenId(tokenId);

    //Submit the query to a Hedera network
    const tokenInfo = await query2.execute(client);

    console.log("The total supply of this token is " +tokenInfo.totalSupply);
```

Error: 

```
node:95546) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'seconds' of null
    at Function._fromProtobuf (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/Duration.cjs:49:14)
    at Function._fromProtobuf (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/token/TokenInfo.cjs:238:42)
    at TokenInfoQuery._mapResponse (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/token/TokenInfoQuery.cjs:133:47)
    at TokenInfoQuery.execute (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/Executable.cjs:216:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:95546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SimiHunjan** [comment]
Confirmed working with v2.0.7. Thank you!
