### ISSUE TITLE
v2.0.5 create file returns AUTORENEW_DURATION_NOT_IN_RANGE

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#305]
```
const transaction12 = await new FileCreateTransaction()
    .setKeys([accountPublicKey]) //A different key then the client operator key
    .setContents("the file contents")
    .setMaxTransactionFee(new Hbar(2))
    .freezeWith(client);

const signTx12 = await transaction12.sign(accountKey);

const submitTx12 = await signTx12.execute(client);

const receipt12 = await submitTx12.getReceipt(client);

const newFileId = receipt12.fileId;

console.log("The new file ID is: " + newFileId);
```
Error:

```
(node:95935) UnhandledPromiseRejectionWarning: StatusError: transaction 0.0.1432@1606811059.343000000 failed precheck with status AUTORENEW_DURATION_NOT_IN_RANGE
    at new PrecheckStatusError (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)
    at FileCreateTransaction.execute (/Users/simihunjan/Desktop/JS2.0.4/node_modules/@hashgraph/sdk/lib/Executable.cjs:210:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:95935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Simis-MacBook-Pro-2:JS2.0.4 simihunjan$
```

**Comment by SimiHunjan** [comment]
Confirmed working in v2.0.7. Thank you!
