### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by emanom** [hashgraph/hedera-sdk-js#329]
Hi, trying to run the SDK examples. I can run get-account-info without error but when I run get-account-balance Node throws the following error:

(node:14660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at Object.fromString (/Users/manuss/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs:65:24)
    at Function.fromString (/Users/manuss/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:38:39)
    at AccountBalanceQuery.setAccountId (/Users/manuss/node_modules/@hashgraph/sdk/lib/account/AccountBalanceQuery.cjs:110:96)
    at main (/Users/manuss/hedera/js-sdk/hedera-sdk-js/examples/get-account-balance.js:35:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:14660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks for your help, I'm not a professional developer.

**Comment by ugh82** [comment]
Hi,

Have you set the environment  values of private key and account id correctly (on the config or .env file?)

**Comment by emanom** [comment]
Yes I have set an .env file as per instructions. I can run get-account-info.js without error.

**Comment by danielakhterov** [comment]
@emanom I can't seem to reproduce this issue. ```> node get-account-info.js
info.key                          = 302a300506032b6570032100ff040efc38b5d822092823b4cf34ca21d1ca44258fe37df064cceae8ff29cca0
info.isReceiverSignatureRequired  = false
info.expirationTime               = Wed Dec 23 2020 00:48:11 GMT-0800 (Pacific Standard Time)
> echo $OPERATOR_ID
0.0.47439
```
