### ISSUE TITLE
Transaction.fromBytes error

### ISSUE THREAD

**Issue by cmdhema** [hashgraph/hedera-sdk-js#332]
When run 'TokenAssociateTransaction.fromBytes(tx.toBytes())' got below error.

TypeError: Cannot read property 'tokens' of null
    at _fromProtobuf (/Users/kjwook/Desktop/kjwook/sources/adb-marketplace/node_modules/@hashgraph/sdk/lib/token/TokenAssociateTransaction.cjs:88:32)
    at Function.fromBytes (/Users/kjwook/Desktop/kjwook/sources/adb-marketplace/node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:221:12)

**Comment by andrix10** [comment]
Thanks for bringing this up, it has been fixed and will be reflected in the next patch.
