### ISSUE TITLE
PrecheckStatusError: failed precheck with status TRANSACTION_EXPIRED

### ISSUE THREAD

**Issue by Stepan-Kirjakov** [hashgraph/hedera-sdk-js#760]
### Description

When performing some transactions (for example AccountCreateTransaction), the thread hangs for 1-2 minutes and exits with an error.
Out of 10 requests are successful 2-6.

Error:

```
PrecheckStatusError: transaction 0.0.1548173@1637331534.191989168 failed precheck with status TRANSACTION_EXPIRED
    at new PrecheckStatusError (D:\work\hashgraph-guardian\vc-modules\node_modules\@hashgraph\sdk\lib\PrecheckStatusError.cjs:23:5)
    at AccountCreateTransaction._mapStatusError (D:\work\hashgraph-guardian\vc-modules\node_modules\@hashgraph\sdk\lib\transaction\Transaction.cjs:944:12)
    at AccountCreateTransaction.execute (D:\work\hashgraph-guardian\vc-modules\node_modules\@hashgraph\sdk\lib\Executable.cjs:392:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (D:\work\hashgraph-guardian\vc-modules\test\stability.js:76:36) {
  status: Status { _code: 4 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: [Long],
      realm: [Long],
      num: [Long],
      _checksum: null
    },
    validStart: Timestamp { seconds: [Long], nanos: [Long] },
    scheduled: false
  }
}
```

### Steps to reproduce

```
const client = Client.forTestnet();
client.setOperator(OPERATOR_ID, OPERATOR_KEY);

for (let i = 0; i < 10; i++) {
	try {
		const newPrivateKey = PrivateKey.generate();
		const transaction = new AccountCreateTransaction()
			.setKey(newPrivateKey.publicKey)
			.setInitialBalance(new Hbar(2));
		const txResponse = await transaction.execute(client);
		const receipt = await txResponse.getReceipt(client);
		const newAccountId = receipt.accountId;
		await wait(1000);
	} catch (error) {
		console.error(error);
	}
}
```

### Additional context

![Скриншот 2021-11-19 20 38 53](https://user-images.githubusercontent.com/84465157/142659080-a8f98538-9b00-482d-b8c0-8a831beb7429.png)

### Hedera network

testnet

### Version

v2.5.0

### Operating system

Windows

**Comment by danielakhterov** [comment]
@SimiHunjan @Stepan-Kirjakov 
I don't believe this is an issue with the SDKs. `AccountCreateTransaction` on the Hedera Service's side has a very low throttle.

**Comment by hanMaster** [comment]
Got same issue
node -v 12.22.7
@hashgraph/sdk: 2.6.0
also tested on 2.4.1
code from get started:


`const { Client, PrivateKey, AccountCreateTransaction, AccountBalanceQuery, Hbar } = require("@hashgraph/sdk");
require("dotenv").config();

async function main() {

    const myAccountId = process.env.MY_ACCOUNT_ID;
    const myPrivateKey = process.env.MY_PRIVATE_KEY;

    if (myAccountId == null ||
        myPrivateKey == null) {
        throw new Error("Environment variables myAccountId and myPrivateKey must be present");
    }

    const client = Client.forTestnet();
    client.setOperator(myAccountId, myPrivateKey);
    //Create new keys
    const newAccountPrivateKey = await PrivateKey.generate();
    const newAccountPublicKey = newAccountPrivateKey.publicKey;

    //Create a new account with 1,000 tinybar starting balance
    const newAccount = await new AccountCreateTransaction()
        .setKey(newAccountPublicKey)
        .setInitialBalance(Hbar.fromTinybars(1000))
        .execute(client);

    // Get the new account ID
    const getReceipt = await newAccount.getReceipt(client);
    const newAccountId = getReceipt.accountId;

    //Log the account ID
    console.log("The new account ID is: " +newAccountId);

    //Verify the account balance
    const accountBalance = await new AccountBalanceQuery()
        .setAccountId(newAccountId)
        .execute(client);

    console.log("The new account balance is: " +accountBalance.hbars.toTinybars() +" tinybar.");
}


main();
`
after freeze about 10-20 seconds got error:

(node:7315) UnhandledPromiseRejectionWarning: StatusError: transaction 0.0.2072949@1639134334.464094668 failed precheck with status TRANSACTION_EXPIRED

**Comment by danielakhterov** [comment]
Yea, the account creation throttle on the Hedera Services nodes is very low which results in in many `BUSY` response codes. What we can and are planning to do is to build a new transaction on the fly with a new transaction ID. This would mean it'd take longer for the request to be submitted, but it shouldn't fail `TRANSACTION_EXPIRED`

**Comment by princefr** [comment]
Any one got a workaround? I cannot create any account in test net because of this.

this is the function I'm calling.

```
async function HederaCreateAccount(publicKey){
  //Create the transaction
  const transaction = new AccountCreateTransaction()
      .setKey(publicKey)
      .setTransactionValidDuration(20);
      

  //Sign the transaction with the client operator private key and submit to a Hedera network
  const txResponse = await transaction.execute(client);

  //Request the receipt of the transaction
  const receipt = await txResponse.getReceipt(client);

  return receipt.accountId
}
```

```
{
    "errors": [
        {
            "message": "transaction 0.0.15720610@1640166893.9892595 failed precheck with status TRANSACTION_EXPIRED",
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ],
            "path": [
                "createUser"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "name": "StatusError",
                    "status": {
                        "_code": 4
                    },
                    "transactionId": {
                        "accountId": {
                            "shard": {
                                "low": 0,
                                "high": 0,
                                "unsigned": false
                            },
                            "realm": {
                                "low": 0,
                                "high": 0,
                                "unsigned": false
                            },
                            "num": {
                                "low": 15720610,
                                "high": 0,
                                "unsigned": false
                            },
                            "_checksum": null
                        },
                        "validStart": {
                            "seconds": {
                                "low": 1640166893,
                                "high": 0,
                                "unsigned": false
                            },
                            "nanos": {
                                "low": 9892595,
                                "high": 0,
                                "unsigned": false
                            }
                        },
                        "scheduled": false
                    },
                    "stacktrace": [
                        "StatusError: transaction 0.0.15720610@1640166893.9892595 failed precheck with status TRANSACTION_EXPIRED",
                        "    at new PrecheckStatusError (/Users/princeondonda/Desktop/work/swoosh_server/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)",
                        "    at AccountCreateTransaction._mapStatusError (/Users/princeondonda/Desktop/work/swoosh_server/node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:944:12)",
                        "    at AccountCreateTransaction.execute (/Users/princeondonda/Desktop/work/swoosh_server/node_modules/@hashgraph/sdk/lib/Executable.cjs:392:22)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
                        "    at async Object.HederaCreateAccount (/Users/princeondonda/Desktop/work/swoosh_server/finance.js:33:22)",
                        "    at async Object.createNewUser (/Users/princeondonda/Desktop/work/swoosh_server/database.js:115:27)"
                    ]
                }
            }
        }
    ],
    "data": null
}

```

**Comment by danielakhterov** [comment]
I believe this is fixed by: https://github.com/hashgraph/hedera-sdk-js/pull/837#event-5897712031
