### ISSUE TITLE
GrpcServiceError: gRPC service failed with status: UNAVAILABLE

### ISSUE THREAD

**Issue by Stepan-Kirjakov** [hashgraph/hedera-sdk-js#765]
### Description

After several (2-4) AccountInfoQuery, requests do not respond (within 10 minutes).

the request is returned inside the handler:
```
GrpcServiceError: gRPC service failed with status: UNAVAILABLE
    at e.rpcImpl (d:\work\tomcat-eco\node_modules\@hashgraph\sdk\lib\channel\NodeChannel.cjs:81:18)
    at e.rpcCall (d:\work\tomcat-eco\node_modules\protobufjs\src\rpc\service.js:94:21)
    at executor (d:\work\tomcat-eco\node_modules\@protobufjs\aspromise\index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (d:\work\tomcat-eco\node_modules\@protobufjs\aspromise\index.js:28:12)
    at e.rpcCall (d:\work\tomcat-eco\node_modules\protobufjs\src\rpc\service.js:86:21)
    at e.getAccountInfo (d:\work\tomcat-eco\node_modules\@hashgraph\proto\lib\proto.js:1:262562)
    at AccountInfoQuery._execute (d:\work\tomcat-eco\node_modules\@hashgraph\sdk\lib\account\AccountInfoQuery.cjs:114:27)
    at CostQuery._execute (d:\work\tomcat-eco\node_modules\@hashgraph\sdk\lib\query\CostQuery.cjs:156:24)
    at CostQuery.execute (d:\work\tomcat-eco\node_modules\@hashgraph\sdk\lib\Executable.cjs:367:31)
```
and has no timeout

### Steps to reproduce

```
const client = Client.forTestnet();
client.setOperator(OPERATOR_ID, OPERATOR_KEY);

for (let i = 0; i < 10; i++) {
    try {
        console.log("execute ", i);
        const info = await new AccountInfoQuery()
            .setAccountId(OPERATOR_ID)
            .execute(client);
        console.log(!!info);
        await wait(1000);
    } catch (error) {
        console.error(error);
    }
}
```

### Hedera network

testnet

### Version

v2.5.0

### Operating system

Windows

**Comment by SimiHunjan** [comment]
Fixed.
