### ISSUE TITLE
Creating 400,000 nfts takes 30+ hours

### ISSUE THREAD

**Issue by anvabr** [hashgraph/hedera-sdk-js#988]
### Description

Our use-case (environmental - carbon units/offsets etc) requires the creation of large number of NFTs which represent these carbon units. Realistically we are unable to achieve objective as it takes more than 30 hours to create 400,000 nfts using the SDK facilities.  We attempted to parallelise the execution however it resulted in duplicate transactions. 

### Steps to reproduce

Use TokenMintTransaction and TransferTransaction SDK facilities to mint a large number of NFTs and transfer them to the owner[s]. Since these API methods can work with up to 10 records, in our use-case it makes 40,000 transactions. 

### Hedera network

testnet

### Version

N/A

**Comment by rbair23** [comment]
Can you post a reproducible example? Currently the network is configured with a setting of 1200 mints per second. The throttles are applied per-node as 1200/N where N is the number of nodes in the network. So if you are testing with a 7 node network and only sending traffic to a single node, then we would expect to see a throttle of 1200/7 or about 171 mints per second, which should still take less than an hour to complete. If you are testing on a 26 node network, then that would be about 46 mints per second or several hours to complete.

There may be a bug in the

**Comment by anvabr** [comment]
@rbair23 do you have tests or sample code that we can take a look at or run which would show this performance? Could you direct us to it please?

**Comment by anvabr** [comment]
@rbair23 and @gregscullard Thank you for your comments. We can't use separate account ID per thread as it is not compatible with our use-case. And when we tried to parallelise with the single account we did indeed get the duplicate transaction IDs.

Here is the extracted code sample which demonstrates the problems.

```
const client = Client.forTestnet();
    client.setOperator(OPERATOR_ID, OPERATOR_KEY);
    const operatorKey = PrivateKey.fromString(OPERATOR_KEY);
    const privateKey = PrivateKey.generate();
    const publicKey = privateKey.publicKey;

    const transaction = new TokenCreateTransaction()
        .setTokenName("Your Token Name")
        .setTokenSymbol("F")
        .setTokenType(TokenType.NonFungibleUnique)
        .setTreasuryAccountId(OPERATOR_ID)
        .setInitialSupply(0)
        .setAdminKey(privateKey)
        .setSupplyKey(privateKey)
        .setMaxTransactionFee(new Hbar(30))
        .freezeWith(client);
    const signTx = await (await transaction.sign(privateKey)).sign(operatorKey);
    const txResponse = await signTx.execute(client);
    const receipt = await txResponse.getReceipt(client);
    const tokenId = receipt.tokenId;
    console.log("The new token ID is " + tokenId);

    const data = [new Uint8Array(Buffer.from("f44dce5b-3b4d-4ea6-aae9-2549bd30f9a2"))];
    const max = 1000;

    //1
    console.time('Start 1');
    for (let i = 0; i < max; i++) {
        const transaction1 = new TokenMintTransaction()
            .setTokenId(tokenId)
            .setMetadata(data)
            .freezeWith(client);
        const signTx1 = await transaction1.sign(privateKey);
        console.log('Execute:', i);
        const txResponse1 = await signTx1.execute(client);
        const receipt1 = await txResponse1.getReceipt(client);
        console.log('Executed:', i);
    }
    console.timeEnd('Start 1');

    //2
    console.time('Start 2');
    let count = 0;
    for (let i = 0; i < max; i++) {
        const clientN = Client.forTestnet();
        clientN.setOperator(OPERATOR_ID, OPERATOR_KEY);
        const transaction1 = new TokenMintTransaction()
            .setTokenId(tokenId)
            .setMetadata(data)
            .freezeWith(clientN);
        const signTx1 = await transaction1.sign(privateKey);
        console.log('Execute:', i);
        signTx1.execute(clientN).then((txResponse1)=>{
            console.log('Executed:', i);
            txResponse1.getReceipt(clientN).then((receipt1)=>{
                count++;
                if(count==max) {
                    console.timeEnd('Start 2');
                }
            }, (error)=>{
                count++
                console.log(error);
                if(count==max) {
                    console.timeEnd('Start 2');
                }
            })
        }, (error)=>{
            count++
            console.log(error);
            if(count==max) {
                console.timeEnd('Start 2');
            }
        });
    }

    await wait(600000);
```

Case 1 runs at about 1s per transaction.  In case 2 we get two types of errors if there are more than 200-300 transactions.

```
StatusError: transaction 0.0.1548173@1647361784.722423145 failed precheck with status INVALID_NODE_ACCOUNT
    at new PrecheckStatusError (d:\work\vctest\node_modules\@hashgraph\sdk\lib\PrecheckStatusError.cjs:23:5)
    at TokenMintTransaction._mapStatusError (d:\work\vctest\node_modules\@hashgraph\sdk\lib\transaction\Transaction.cjs:1068:12)
    at TokenMintTransaction.execute (d:\work\vctest\node_modules\@hashgraph\sdk\lib\Executable.cjs:420:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {name: 'StatusError', status: Status, transactionId: TransactionId, stack: 'StatusError: transaction 0.0.1548173@16473617…ions (node:internal/process/task_queues:96:5)', message: 'transaction 0.0.1548173@1647361784.722423145…ed precheck with status INVALID_NODE_ACCOUNT'}
```
Or
```
StatusError: transaction 0.0.1548173@1647361778.618899118 failed precheck with status DUPLICATE_TRANSACTION
    at new PrecheckStatusError (d:\work\vctest\node_modules\@hashgraph\sdk\lib\PrecheckStatusError.cjs:23:5)
    at TokenMintTransaction._mapStatusError (d:\work\vctest\node_modules\@hashgraph\sdk\lib\transaction\Transaction.cjs:1068:12)
    at TokenMintTransaction.execute (d:\work\vctest\node_modules\@hashgraph\sdk\lib\Executable.cjs:420:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {name: 'StatusError', status: Status, transactionId: TransactionId, stack: 'StatusError: transaction 0.0.1548173@16473617…ions (node:internal/process/task_queues:96:5)', message: 'transaction 0.0.1548173@1647361778.618899118…d precheck with status DUPLICATE_TRANSACTION'}
```

**Comment by anvabr** [comment]
We will test it and come back to you  @gregscullard , thank you for the suggestion!

**Comment by anvabr** [comment]
@gregscullard Thank you for the suggestion on how to fix `DUPLICATE_TRANSACTION` issue, we've tested and it resolved the issue. However we now get Hedera error, it feels like we are DOSing it with the volume of requests (see below). Any suggestions here please?
```
GrpcServiceError: gRPC service failed with status: UNAVAILABLE
    at e.rpcImpl (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\@hashgraph\sdk\lib\channel\NodeChannel.cjs:81:18)
    at e.rpcCall (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\protobufjs\src\rpc\service.js:94:21)
    at executor (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\@protobufjs\aspromise\index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\@protobufjs\aspromise\index.js:28:12)
    at e.rpcCall (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\protobufjs\src\rpc\service.js:86:21)
    at e.mintToken (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\@hashgraph\proto\lib\proto.js:1:276552)
    at TokenMintTransaction._execute (C:\Users\tmf\Projects\WaveAccess\guardian\threads-test\node_modules\@hashgraph\sdk\lib\token\TokenMintTransaction.cjs:209:26)
```

**Comment by danielakhterov** [comment]
Converting this issue into a discussion since it's not an issue with the JS SDK.
